<!-- BEGIN MESSAGE -->
{MESSAGE}<br /><br />
<!-- END MESSAGE -->

{START_FORM}
{SHOWBLOCK} {SHOWBLOCK_LABEL}<br /><br />

{BLOCKTITLE_LABEL}:<br />
{BLOCKTITLE}<br /><br />

{MODE_LABEL}: {MODE_HELP}<br />
{MODE_1} {MODE_1_LABEL}<br />
{MODE_2} {MODE_2_LABEL}<br />
{MODE_3} {MODE_3_LABEL} {CURRENT}<br /><br />

{RESIZE_LABEL}: {RESIZE_HELP}<br />
{RESIZE_WIDTH} X {RESIZE_HEIGHT} {PIXELS_LABEL}
<!-- BEGIN GD_LABEL -->
<i>({GD_LABEL})</i>
<!-- END GD_LABEL -->
<br /><br />

{SAVE_BUTTON}
{END_FORM}